language: node_js
addons:
  apt:
    packages:
    - libimage-exiftool-perl
node_js:
- node
install:
- yarn -i
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: K5wIbgvMxJ8pvTEand/WuzG19aH1RplSzA7bKDReN6y7C0VWWbPQIDbbmf5lpY5pR7fgyjLHZNwQjPcF/Rm7hUJImHTUEed6YFvcmCFNoyDT/r7VHLTMWJEoeEWR+HYpHLcXR3I49yDAHmhHPkRmdgx3W4QrIo53OrfeAGgYsA1WNyAg2AxBTdbYVC+bEsezIsoBy15i+c0u1gVEY/ztBrYgAIc7Gfs53O86VQp/DV3euQ3ID3rVpDS7mQBtbS+MJlECMcwZnnh1duPGJ6JE8rpoHfNGJZfj+8JkucQZNoJQ9S5BaAhZqiLjsypHhIj1tzkNmJ9rJEStxIChCXu/SYQtDt/f/slb+HzLn3hBsSlnauwSldvuBt6TodnQiSQ3yEaJQyWHqxG8M5vv9K7hZwdKaAR1NA3Vhr7Gw5opPrs9/7l6Rp/sVhxejWYXLwgFwT1dcp7HOtqxDEig28lKLI3P7nZW3juw5/zl12fzAlrKt9GBU1DB9d648Mpfzl6d1vqrS0ANIvXlhJ+W2roWeLuEbIU4N1Zd5ZxWBIMRjMm3/xNDKWCd5v41eVPrH+yfxVrwYUd/zevxFjwhDCVDv6XtaUYEssjAJQVg/BCWquweADG18hybKRUBFg/5qgPcX0W8FwKD5zLKSvGB4M8YFZqjUfPH7AqkBMVdMbEhe5o=
  on:
    tags: true
    repo: softbrix/vega_media_info
