language: node_js
addons:
  apt:
    packages:
    - libimage-exiftool-perl
node_js:
- node
install:
- yarn -i
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: H7+Q9VN6PvvSUMC0OJbJsgwhwQZhrAHMDKpJkP5NwRahneXUgrrza/wiyPJFj4thuNwseqZQGSAcHXoBjm0G/5lYcPRC1buea7BLyRXy2nwz7618Q68AaZ4HRZNtR11h9admsFMwad7bMcuPqGM64l6BTzyMpJzhGUd4DxOyP+VxtXxwhzm3efWxZn+v7rKDiCyXJhkDzWyyIsaSV4vggutNep1tiUxXa3MSS+f8OhLFb67kC+4ZFpshTqEFjnAT96gUL2jWGTWF4OnW77x8Rl0itLrBwjqxaL+6ROEtJzvkA0hjGPGX08yJhIyUzdFn3jtplGdMaNVRgp5x3zaLFaUNIlkPmWvbdyFVKxdN1x/PtqAHEXnZSCX/oRVfv7WyBD/axFyTgsKZ8aADdQ4w9547em9Aay7mkw6TxnG2Nh18Bvh+P4nJBF3Dxcmp3Fh39JZw0EyQbwk0Bltmz/WLfhkmMwBx+sUhu+eyu1N/NwMkJjbjdk8++DyZol6ogShXmumf8CpKpe/Tq+xeoItIQep1l53St+0JpWuuFCUu/jgUkNYyyBRl8F9io2AnyIEIjWVHhbR8HPHXW0zKsn8zO9KM1Vt4ACWc80Q4jsX+IORkfrBZvzfnxGvTzOvmGOBluLJrkvbGJwFAO/9ME+tkvs60SXn9yR8kAtNCEMu3nn4=
  on:
    tags: true
    repo: softbrix/vega_media_info
