language: node_js
addons:
  apt:
    packages:
    - libimage-exiftool-perl
node_js:
- node
install:
- yarn -i
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: ZuiFaBBq9lrKqmFWToVLY3U5imxlF3wwL/hgp6f1qpM/uAKkByGdgWTfpCPl0Ev8gAUqzp3EnbG3OHJa4Xj3PZgTTdxqMEXDYe1uOsncVhKioLwUHfXzDtX8M4jLA+7dD/RMMP0+UVA7VvzwhhUNRdg4DerktoPwEwgLofa9oYR7K99HvPypWg337KAcojtvah4OWdGFbua1Va5WHg6Ohod2v9LvTLrktpXw1txmAC0EXGHtjjZvS+sHNeNIixklAl2fLHoek491PbxdG+pXH674rdrMa1AF+rTVErCAL3obfJWyW5+afSbRjP/ckTj7ixoSrY8nMsfo7gGPhcqMG7uiXSwuv5s0T3/bRmVdSW+5P8gdajpjL9DCAWAQx8/yyXGw8NjPc2v0gPSToIptHl4RQ0G/FOj8jyfcsK1RhlWZzrucBkq3h6PgVBJZOjk7mp3/cvXpWkWfq4TVNnvoYu1v6jZZ8VvNgRmAD7uK7i9sRflOK/eoo8ehpKeOeFoYMLKfTqVmE/1qcS4SB7oxOz0aMoAQVIX7zaHmUiymA4vL6JV6ebSB/PnxrosOQXD4jc+uog9G2aoj1p0kiA3KkP8q+jLszhCFcKylL4XcYBxVT3jZh9zJfvsvot1vJpiNQg1ScHj5dYL3a4t+sZSAIR92K8webjgyctqEdb1dTZg=
  on:
    tags: true
    repo: softbrix/vega_media_info
